language: python
python:
  - "3.7"

branches: master  # This way push builds will only run on master branch. Does not affect PR builds.

cache: pip

install:
  - pip install flake8

script:
  - git diff --name-only HEAD...$TRAVIS_BRANCH | flake8 --diff .
